- README.md
- package-lock.json
added the 3 values that can be provided
- wallet in base58
- rpc address
- open ai key
> improved the example new agent declaration

- test/index.ts
https://www.solanaagentkit.xyz
> Update index.ts with new url

- README.md
- guides/add_your_own_tool.md
- package.json
- pnpm-lock.yaml
- src/agent/index.ts
- src/langchain/index.ts
- src/tools/index.ts
- src/tools/pyth_fetch_price.ts
- src/types/index.ts
Added tool to grab price data from Pyth
> feat: Add Pyth support

- guides/add_your_own_tool.md
- guides/test_it_out.md
This PR adds updates to the guides:
> `test_it_out.md`
- Fixed outdated code examples
> `add_your_own_tool.md`
- Prepend filename hints to code snippets (for easier navigation)
- Add more code snippets for agent usage and custom tool usage
> Update guides content and code snippets

- README.md
Added a PR to add the star graph and the contributors on the home README.md page
> Updated README.md with contributors and star graph

- examples/persistent-agent/README.md
**Fix Typo in `README.md`**
This pull request corrects a minor typo in the `README.md` file for the `persistent-agent` example. Specifically, "ur PostgreSQL databse" was corrected to "your PostgreSQL database" for improved readability and professionalism.
- **File Modified:** `examples/persistent-agent/README.md`
- **Summary of Changes:**  
- Corrected "databse" to "database."
This change is purely editorial and does not affect the functionality or structure of the code.
---
**Allow edits by maintainers:** [x]
> typo fix Update README.md

- README.md
- src/agent/index.ts
- src/constants/index.ts
- src/idls/adrena.ts
- src/langchain/index.ts
- src/tools/adrena_perp_trading.ts
- src/tools/index.ts
- src/utils/AdrenaClient.ts
Add support for Open/Close PERP trade in the agent.
Rely on adrena IDL (anchor) and custom `src/utils/AdrenaClient.ts` to derive necessary PDA and build `openOrIncreasePositionWithSwapLong`, `openOrIncreasePositionWithSwapShort`, `closePositionLong` and `closePositionShort` instructions.
Tested with the following:
```
const signature = await agent.openPerpTradeLong({
price: 300, // $300 SOL Max price
collateralAmount: 0.1, // 0.1 jitoSOL in
collateralMint: new PublicKey("J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"), // jitoSOL
leverage: 50000, // x5
tradeMint: new PublicKey("J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn"), // jitoSOL
slippage: 0.3, // 0.3%
});
```
https://explorer.solana.com/tx/33iLQ7BrS5xpMfhrXDGzCjrP3g7BHH63Sv6QEQw5qBzP2YnHVjNL9iHEDkDdzw2cF6zYECGVzoUV6qjth7r4wioT
and …
> Add Adrena Protocol Open/Close PERP trade support

- pnpm-lock.yaml
- src/tools/orca_close_position.ts
- src/tools/orca_create_clmm.ts
- src/tools/orca_create_single_sided_liquidity_pool.ts
- src/tools/orca_open_centered_position_with_liquidity.ts
- src/tools/orca_open_single_sided_position.ts
- src/utils/keypair.ts
Fixes # (issue number)
- Created a custom Wallet class to support browser use of Orca tools
Example transaction: https://solscan.io/tx/GNmgxM4ZRHURDWcgmhLmBrSG5RgF9yw5B4jzEXzWX2jpNvCbUsQyaMdkkH77au7pisJ89hJdrcs8dv54U8H3J8V?cluster=devnet
Using Devnet
```
i want to open a single sided position in pool 7MghXMotsf9CLr6Z9obV8g9Kt2y1Mqn6wXm2mdPhRnMe
```
then provide details
> Update browser wallet for Whirlpools SDK

- .github/workflows/build.yml
This PR fixes the failing CI workflow
> fix: failing CI workflow

- README.md
Update the `15+ actions` in the readme to `60+ actions`
> Update README.md: change 15+ actions to 60+ actions

- package.json
- pnpm-lock.yaml
- turbo.json
This PR updates turbo and fixes a config issue.
> Fix: turbo update and config

- src/actions/elfa_ai/elfa_ai_actions.ts
- src/tools/coingecko/get_token_price_data.ts
- src/tools/coingecko/get_trending_tokens.ts
- src/types/index.ts
This PR adds support for devs to use their coingecko demo api key to get token price data and trending tokens
> feat: Add support for coingeck o demo api key

- CONTRIBUTING.md
"Check" is a more direct and concise verb than "Check out," making the sentence clearer and more formal.
> Improving CONTRIBUTING.md Documentation

- src/actions/drift/createDriftUserAccount.ts
- src/utils/flashUtils.ts
This PR corrects spelling errors in the following files:
- `createDriftUserAccount.ts`: Fixed a typo in `symobl` → `symbol` in the success message.
- `flashUtils.ts`: Corrected multiple occurrences of `hemrmesPriceUdpate` → `hermesPriceUpdate` to ensure consistency and accuracy in fetching oracle price updates.
> Fix typos in `flashUtils.ts` and `createDriftUserAccount.ts`

- examples/agent-kit-nextjs-langchain/app/page.tsx
https://https://www.solanaagentkit.xyz - https://www.solanaagentkit.xyz --- deleted `https://`
> fix url typo page.tsx

- src/tools/debridge/createBridgeOrder.ts
Fixes deBridge Integration Analytics
- Add the tracker for Solana Agent Kit usage
> feat: Fix debridge Integration Analytics

- examples/tg-bot-starter/advanced-tg-bot/src/app/api/bot/route.ts
> fix error route.ts

- packages/adapter-mcp/package.json
- packages/adapter-mcp/tsconfig.cjs.json
- packages/adapter-mcp/tsconfig.json
- packages/core/package.json
- packages/core/tsconfig.cjs.json
- packages/core/tsconfig.json
- packages/plugin-blinks/package.json
- packages/plugin-blinks/tsconfig.cjs.json
- packages/plugin-blinks/tsconfig.json
- packages/plugin-defi/package.json
- packages/plugin-defi/tsconfig.cjs.json
- packages/plugin-defi/tsconfig.json
- packages/plugin-misc/package.json
- packages/plugin-misc/tsconfig.cjs.json
- packages/plugin-misc/tsconfig.json
- packages/plugin-nft/package.json
- packages/plugin-nft/tsconfig.cjs.json
- packages/plugin-nft/tsconfig.json
- packages/plugin-token/package.json
- packages/plugin-token/tsconfig.cjs.json
- packages/plugin-token/tsconfig.json
- pnpm-lock.yaml
- test/index.ts
- test/package.json
- test/tsconfig.json
This PR adds support for CommonJS compatibility.
- Added CJS and ESM file paths that are generated during builds
Some packages and apps still compile to CJS for some inexplicable reason 🤦‍♂️ so in order to have the best compatibility CJS builds need to be added.
> chore: add compatibility for cjs and esm

- .npmignore
- packages/adapter-mcp/.npmignore
- packages/adapter-mcp/package.json
- packages/core/.npmignore
- packages/core/package.json
- packages/plugin-blinks/.npmignore
- packages/plugin-blinks/package.json
- packages/plugin-defi/.npmignore
- packages/plugin-defi/package.json
- packages/plugin-misc/.npmignore
- packages/plugin-misc/package.json
- packages/plugin-nft/.npmignore
- packages/plugin-nft/package.json
- packages/plugin-token/.npmignore
- packages/plugin-token/package.json
Types were not working for CJS module resolved apps.
- I just changed the types parameters to reference the cjs types instead of the esm types.
- Added npmignore and remove tsconfig
> Chore: change types parameter to use cjs

- examples/agent-kit-nextjs-langchain/app/api/chat/route.ts
- examples/discord-bot-starter/src/index.ts
- examples/market-making-agent/index.ts
- examples/orbofi-personality-engine/index.ts
- examples/persistent-agent/index.ts
- examples/tg-bot-starter/advanced-tg-bot/src/app/api/bot/route.ts
- examples/tg-bot-starter/basic-tg-bot/src/app/api/bot/route.ts
- test/agent_sdks/vercel_ai.ts
- test/index.ts
Removed the line about requesting funds from the faucet from the system prompt. This implicitly tells the agent that it's on the devnet even when not true.
- Just removed the line about the faucet from the system prompt
> remove faucet line from system prompt

- packages/plugin-misc/src/index.ts
Fixes a merge conflict with miss during the messariAI feature merge.
- Fix the merge conflict that we missed in the messariAI PR merge
> v2:fix: MessariAI merge conflict
